assignment/urls.py
from django.urls import path
# from .views import UserListView
from . import views
from cruds_adminlte.urls import crud_for_model
from .forms import SelectCourseForm
from .models import SelectCourse
from django.conf import settings
from .views import GradeUpdateView, StatusUpdateView, CourseUpdateView


app_name = 'assignment_app'
urlpatterns = [
    path('register_course/<int:pk>/', views.register_course, name='register-course'),
    path('main_dashboard/<int:pk>/', views.main_dashboard, name='main-dashboard'),
    path('assignment/<int:pk>/<int:i_n>/', views.submit_assignment, name='submit-assignment'),
    path('assignment/delete/<int:pk>/<int:i_n>/', views.del_assignment, name='delete-assignment'),
    path('assignment/update/<int:pk>/', views.update_assignment, name='update-assignment'),
    path('assignment/view_assignment_pdf/<int:pk>/', views.viewAssignmentPDF, name='view-assignment-pdf'),
    path('download_assignment/<int:pk>/', views.download_pdf, name='download-file'),
    path('score_student_section/<int:pk>/', views.student_result, name='score-student-section'),
    path('assignment/all_students/<int:pk>/', views.all_students, name='all-students'),
    path('assignment/dashboard/', views.dashboard, name='dashboard'),
    path('assignment/submission_denied/<int:pk>/<int:i_n>/', views.submission_denied, name='submission-denied'),
    path('assignment/score_student_section/update/<int:pk>/', GradeUpdateView.as_view(), name='update-grade'),
    
    path('course/update/<int:pk>/', views.update_courses, name='update-courses'),
    
    path('update/<int:pk>/', views.update_submitted, name='update-status'),
    path('view_result/<int:pk>/<int:i_n>/', views.query_results, name='view-result'),
    path('all_courses/<int:pk>/', views.all_courses, name='all-courses'),
    path('del_courses/<int:pk>/', views.del_course, name='del-course'),
    path('del_upload_file/<int:pk>/', views.del_upload_file, name='del-upload-file'),
    path('student_dashboard/', views.student_dashboard, name='student-dashboard'),
    path('del_choose_course/<int:pk>/', views.del_choose_course, name='del-choose-course'),
    path('create_pdf/', views.create_pdf, name='create-pdf'),
    path('reults_denied/<int:pk>/', views.results_denied, name='results-denied'),

    path('pdf_view/', views.ViewPDF.as_view(), name="pdf-view"),
    path('pdf_download/', views.DownloadPDF.as_view(), name="pdf-download"),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += crud_for_model(SelectCourse, views=['all_courses'],
                    add_form=SelectCourseForm, update_form=SelectCourseForm )

students_record/urls.py
from django.contrib import admin
from django.urls import include, path

from users import views
from django.contrib.auth import views as auth_views
# from users.views import CustomLoginView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
    path('', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('assignment/', include('assignment.urls', namespace='assignment_app')),
    path('admin/', admin.site.urls),
    path('register_student/', views.register, name='register'),
    path('profile/<int:pk>/<int:i_n>/', views.profile, name='profile'),
    path('back/<int:pk>/', views.back, name='back'),
    path('login_success/', views.login_success, name='login-success'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

]

# , namespace='assignment-section')
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

users/urls.py
# from django.urls import path
# from . import views
# from django.conf import settings
# from django.contrib.auth import views as auth_views
# from .views import CustomLoginView

# urlpatterns = [
#     path('', views.register, name='register'),
#     path('profile/', views.profile, name='profile'),
#     path('login/', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
#     path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

# ]


# if settings.DEBUG:
#     from django.conf.urls.static import static
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignment/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.http import JsonResponse
from .forms import (ImageFileUploadForm, FilesForm, StudentResultForm, 
                        StudentResultForm2, UploadedFileForm, 
                        RegisterCourseForm, SemesterForm, SelectCourseForm, StudentOtherCourseForm)
from .models import (Profile, Assignment, StudentResult, 
        UploadedFile, RegisterCourse, Semester, StudentOtherCourse, SelectCourse)
from django.contrib.auth import get_user_model
from django.views.generic import UpdateView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import ObjectDoesNotExist
import datetime
import os
import random
from django.conf import settings
from django.http import FileResponse, Http404, HttpResponse, HttpResponseRedirect
from django.utils import timezone
from datetime import datetime as dt
from encrypted_id import ekey

import io
from django.http import FileResponse
from reportlab.pdfgen import canvas

from io import BytesIO
from django.template.loader import get_template
from django.views import View
from xhtml2pdf import pisa

# from users.models import SelectCourse

User = get_user_model()

@login_required
def submit_assignment(request, pk, i_n):
    o_t = StudentOtherCourse.objects.get(id=i_n)
    # user = User.objects.get(pk=o_t.user.pk)
    sel = SelectCourse.objects.get(pk=pk)
    # o_t = StudentOtherCourse.objects.get(choose_course=sel.courses)
    # print(o_t)
    # us = User.objects.filter(course=o_t.choose_course).exclude(index_number=request.user) #filter(course=s_c.courses)
    s = Semester.objects.first()
    rn = random.randint(1, 200)
    date = datetime.date.today()
    if request.method == 'POST':
        form = FilesForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            submission_date = ""
            try:
                u = UploadedFile.objects.filter(course=sel.courses).first()
                submission_date = str(u.submission_date) # will come from database
            except AttributeError:
                return HttpResponseRedirect(reverse('assignment_app:submission-denied', args=(pk,i_n,)))
            curr_date = str(date)
            # if curr_date <= submission_date:
            pdf_file = form.cleaned_data.get('file')
            _, e = os.path.splitext(str(pdf_file))
            if e in ['.pdf', 'txt']:
                assignment = Assignment.objects.create(pdf_file=pdf_file,
                            index=o_t.user.index_number, status='submitted', q_number=rn, date_submitted=date, date_created=timezone.now(), user=o_t.user, studentothercourse=o_t, course=sel.courses)
                return HttpResponseRedirect(reverse('assignment_app:submit-assignment', args=(sel.pk,i_n,)))
            else:
                return JsonResponse({'error': True, 'errors': 'File type('+e+') not supported'})
            # else:
            #     return HttpResponseRedirect(reverse('assignment_app:submission-denied', args=(user.pk,)))

    else:
        form = FilesForm()

    ass= Assignment.objects.filter(user=o_t.user).filter(course=o_t.choose_course).order_by('-date_created')
    
    r =  StudentResult.objects.order_by('-date_graded1').filter(course=sel.courses).filter(user=o_t.user)
    query = request.GET.get('q')
    print(query)
    if query:
        r =  StudentResult.objects.order_by('-date_graded1').filter(course=sel.courses).filter(user=o_t.user).filter(q_number=query)
  
    context = {
        'assignment': Assignment.objects.filter(user=o_t.user).filter(course=o_t.choose_course).order_by('-date_created'),
        'assigncount': Assignment.objects.filter(user=o_t.user).filter(course=o_t.choose_course).count(),
        'u_file': UploadedFile.objects.filter(course=sel.courses).order_by('-date_created'),
        'c_file': UploadedFile.objects.all(),
        'result': r,
        'prof': sel.user,
        's': s,
        'sel': sel,
        # 'us': us,
        'o_t': o_t,
     
    }


    return render(request, 'assignment/index.html', context)


def query_results(request, pk, i_n):
    o_t = StudentOtherCourse.objects.get(id=i_n)
    # sel = SelectCourse.objects.get(pk=pk)  
    r = StudentResult.objects.filter(q_number__icontains=17)
    return HttpResponseRedirect(reverse('assignment_app:submit-assignment', args=(o_t.selectcourse.pk,i_n)))



def submission_denied(request, pk, i_n):
    context = {
        'cur_user': pk,   #User.objects.get(pk=pk)
        'i_n': i_n,
    }
    return render(request, 'assignment/submission_denied.html', context)


def results_denied(request, pk):
    context = {
        'c_pk': pk,
    }
    return render(request, 'assignment/results_denied.html', context)


def dashboard(request):

    if request.user.is_staff or request.user.is_superuser:
        return HttpResponseRedirect(reverse('assignment_app:all-courses', args=(request.user.pk,)))
    return HttpResponseRedirect(reverse('assignment_app:student-dashboard'))

    user = User.objects.get(index_number=request.user.index_number)
    context = {
        'u': user
    }
    return render(request, 'assignment/dashboard.html', context)



@login_required
def del_assignment(request, pk, i_n):
    import os
    
    ass = Assignment.objects.get(pk=pk)
    o_t = StudentOtherCourse.objects.get(pk=i_n)
    # sel = SelectCourse.objects.get(pk=o_t.)
    date = datetime.date.today()
    submission_date = ''
    try:
        u = UploadedFile.objects.first()
        submission_date = str(u.submission_date)
    except AttributeError:
        return HttpResponseRedirect(reverse('assignment_app:submission-denied', args=(pk,)))
    curr_date = str(date)
    if curr_date <= submission_date:
        f_name = os.path.join(settings.MEDIA_ROOT, str(ass.pdf_file))
        ass.delete()
        os.remove(f_name)
        return HttpResponseRedirect(reverse('assignment_app:submit-assignment', args=(o_t.selectcourse.pk,i_n,)))
    return HttpResponseRedirect(reverse('assignment_app:submission-denied', args=(pk,)))


@login_required
def update_assignment(request, pk):
    ass = get_object_or_404(Assignment, pk=pk)
    form = FilesForm(request.POST or None,
                    request.FILES or None)
    return HttpResponseRedirect(reverse('assignment_app:submit-assignment'))


@login_required
def viewAssignmentPDF(request, pk):
    import os
    from django.conf import settings
    get_file = Assignment.objects.get(pk=pk)
    f_name = os.path.join(settings.MEDIA_ROOT, str(get_file.pdf_file))
    file_name, file_ext = os.path.splitext(f_name)
    if file_ext in ['.pdf', '.txt', '.py']:
        pdf = open(f_name, 'rb').read()
        return HttpResponse(pdf, content_type='application/'+file_ext[1:])


def django_image_and_file_upload_ajax(request):
    if request.method == 'POST':
       form = ImageFileUploadForm(request.POST, request.FILES)
       if form.is_valid():
           form.save()
           
           return JsonResponse({'error': False, 'message': 'Uploaded Successfully'})
       else:
           return JsonResponse({'error': True, 'errors': form.errors})
    else:
        form = ImageFileUploadForm()
        return render(request, 'assignment/upload.html', {'form': form})



def show_files(request):
    obj = Profile.objects.all()
    return render(request, 'assignment/show_files.html', {'object': obj})


@login_required
@staff_member_required
def student_result(request, pk, model_class=StudentResult, form_class=StudentResultForm):
    # user = User.objects.get(pk=pk)
    o_c1 = StudentOtherCourse.objects.get(pk=pk)

    # ass = Assignment.objects.get(pk=pk)
    # print(ass.pk)
    # sel = SelectCourse.objects.get(pk=pk)
    o_c = StudentOtherCourse.objects.filter(user=o_c1.user).filter(choose_course=o_c1.choose_course)
    # sel = SelectCourse.objects.filter(courses=user.course).first()

    try:
        # u = User.objects.get(pk=pk)
        a = Assignment.objects.filter(index=o_c1.user.index_number).first()
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('assignment_app:score-student-section', args=(pk,)))
    if request.method == 'POST':
        form = StudentResultForm(o_c1, request.user, request.POST)
        if form.is_valid:
            print(form.errors)
            obj = form.save(commit=False)
            form.instance.user = o_c1.user
            form.instance.studentothercourse = o_c1
            form.instance.assignment = a
            # update status in assignment
            obj.status = form.cleaned_data.get('status')
            obj.q_number = form.cleaned_data.get('q_number')
            assign = Assignment.objects.filter(user=o_c1.user).filter(course=o_c1.choose_course)
            q_num_list = [a1.q_number for a1 in assign]
            a2 = Assignment.objects.filter(q_number=obj.q_number).first()
            if obj.course != o_c1.choose_course:  #   :
                return HttpResponseRedirect(reverse('assignment_app:results-denied', args=(pk,)))
            
            a = Assignment.objects.filter(index=a.index).filter(q_number=obj.q_number).update(status=obj.status)
            form.save()
            return HttpResponseRedirect(reverse('assignment_app:score-student-section', args=(pk,)))
    else:
        form = StudentResultForm(o_c1, request.user)

    
    s_a = Assignment.objects.order_by('-date_created').filter(course=o_c1.choose_course).filter(user=o_c1.user)
    context = {
        'form': form,
        'ass': s_a,
        'u': o_c1.user,
        'sel': o_c,
        'o_c1': o_c1,
    }
    return render(request, 'assignment/studentresult_update_form.html', context)


@login_required
@staff_member_required
def all_students(request, pk):
    
    all_staff = User.objects.filter(is_staff=True)
    list_all_staff = [s.index_number for s in all_staff]

assignment/templates/assignment/all_courses.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
        <header style="height: 5vh;">
            <nav class="navbar navbar-expand-lg navbar-light bg-info">
                <div style="position: relative; left: 0;">
                    <a class="navbar-brand ml-4 text-white" id="b__fnt" href="#">KNUST</a> |
                    <span style="color: white;"> {{ semester.sem|upper }}</span>
                </div>
                <div id="p__o" style="position: absolute; right: 0;">
                    <a href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
                </div>

                </div>
            </nav>
        </header>
            <main>
                <div class="all-courses-wrapper">
                    <!-- semester -->
                    <div class="row ml-3 mr-3 pt-2">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body h-20">
                                    <div id="form__wrapper">
                                        <!-- select semester -->
                                        <form method='POST' action=".">{% csrf_token %}
                                            {{ s_form|crispy }}
                                            <button type="submit" class="btn btn-success">Set</button>
                                        </form>
                                        <!-- create course -->
                                        <hr style="background: black;">
                                        <form method='POST' action="." class="pt-2 blck">{% csrf_token %}
                                            <div>{{ c_form|crispy }}</div>
                                            <div>
                                                <button type="submit" class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- ------- -->
                    
                    
                <!-- --------------- -->
                <!-- <a href="{% url 'assignment_app:create-pdf' %}" class="pr-4">Create Pdf</i></a> -->
                <div class="scrol-vertically mr-4 ml-4">
                        
                        {% for s in a_c %}
                                <div class="vt-card" style="background-image: linear-gradient(180deg,{{ s.choose_back_color }}, white);" onclick=location.href="{% url 'assignment_app:all-students' s.pk %}";>
                                    <span id="del__cse"><a href="#"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></a></span>
                                    
                                    <div class="std-dialog">
                                        <a href="{% url 'assignment_app:update-courses' s.pk %}" class="pr-4"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                        <a href="{% url 'assignment_app:del-course' s.pk %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                    </div>

                                    <div id="del__v">
                                        {{ s.courses }}
                                        <hr>
                                        <div style="font-size: 17px;">
                                            Number of students 
                                        </div>
                                        <div>{% cal_course s.pk %}</div>
                                    </div>
                                </div>
                        {% endfor %}
                        
                    </div>
                

                <!--  -->

        
                </div>
      
            </main>

        <footer class="ft" style="height: 5vh;">
            <div>
                &copy All rights reserved
            </div>
        </footer>
{% endblock %}

assignment/templates/assignment/assignment_update_form.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
<div class="register-course">
    <div class="row">
        <div class="col-md-12">
            <div class="card bg-dark">
                <div class="card-body">
                    <form method="POST" action="." enctype="multipart/form-data" id="f__c">{% csrf_token %}
                        {{ form|crispy }}
                        <div class="form-group" id="r__c">
                            <div>
                                <button class="btn btn-outline-success" type="submit">Save</button>
                            </div>
                            <div>
                                <a class="btn btn-danger" href="{% url 'assignment_app:all-students' %}" role="button">Cancel</a>                
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

assignment/templates/assignment/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">   
    <link rel="stylesheet" href="{% static 'assignment/upload.css' %}">  
    <link rel="stylesheet" href="{% static 'assignment/register.css' %}">  
    <link rel="stylesheet" href="{% static 'assignment/login.css' %}">  
    <link rel="stylesheet" href="{% static 'users/register.css' %}">  
    <title>Students Record</title>
    {% block head %}{% endblock %}
</head>
<body>
    
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message }} bg-info text-white">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message}}
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

assignment/templates/assignment/dashboard.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
    <div class="dashboard-wrapper">
        <a href="{% url 'submit-assignment' u.pk %}">Submit assignment</a>
    </div>
{% endblock %}

assignment/templates/assignment/main_dashboard.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
<div class="course-wrapper">
    <a class="btn btn-primary" href="{% url 'assignment_app:submit-assignment' cur_user.pk %}" role="button">Integral Equations</a>
    <a class="btn btn-primary" href="{% url 'assignment_app:submit-assignment' cur_user.pk %}" role="button">Real functions</a>
</div>
{% endblock %}

assignment/templates/assignment/results_denied.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
    <div class="denied-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body text-center p-2" id="text-wrap">
                        <a href="{% url 'assignment_app:score-student-section' c_pk %}"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>
                        Grading of student denied!!!
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

assignment/templates/assignment/student_dashboard.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-info">
            <div style="position: relative; left: 0;">
                 <a class="navbar-brand ml-4 text-white" id="b__fnt" href="{% url 'assignment_app:student-dashboard' %}">KNUST</a>|
                <span style="color: white;"> {{ s.sem|upper }}</span>
            </div>
            <div id="p__o" style="position: absolute; right: 0;">
                <a href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
            </div>

            </div>
        </nav>
    </header>
    <main>
    <div class="dashboard-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body bg-dark">
                        <form method="POST" action="." enctype="multipart/form-data" id="f__c">{% csrf_token %}
                            {{ o_form|crispy }}
                            <div class="other-std">
                                <div>
                                    <button class="btn btn-outline-success" type="submit">Save</button>
                                </div>
                                <div>
                                    <a class="btn btn-danger" href="{% url 'logout' %}" role="button">Cancel</a>                
                                </div>
                            </div>
                        </form>
    
                    </div>
                </div>
            </div>
        </div>

        <hr style="background: blanchedalmond;">
        <div class="mt-4">
            {% for os in o_course %}
                <div id="dash__click" style="border-left: solid {{ os.selectcourse.choose_back_color }};" class="row h-20 text-dark mt-4" onclick=location.href="{% url 'assignment_app:submit-assignment' os.selectcourse.pk os.pk %}";>
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-body" id="deco" style="background-image: linear-gradient(90deg, white, {{ os.selectcourse.choose_back_color }});">
                                <span class="de-ass" style="background: {{ os.selectcourse.choose_back_color }};" href="#" ><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                                
                                <div class="de-dialog p-2">
                                    This will completely delete any associated activity,
                                    want to delete?
                                    <a href="{% url 'assignment_app:del-choose-course' os.pk %}" > Yes</a>
                                </div>
                                <div class="f-size" style="font-size: 1.5em; font-weight: 500;">{{ os.choose_course }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    </main>
{% endblock %}

assignment/templates/assignment/studentresult_update_form.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
    <div id="h__w1">
        <div id="h__w">
            
            <div class="b">
                {% if o_c1 %}
                    <a href="{% url 'assignment_app:all-students' o_c1.selectcourse.pk %}"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>
                {% endif %}
            </div>
            <div class="h">
                <h4>GRADE STUDENT</h4>
            </div>
        </div>
    </div>
   
    <div class="main-wrapper1">
        <div class="students-wrapper">
            <div class="students-items">
                {% for s in ass %}
                    <div class="c-vertical">
                        <h5 id="q__n">Q number: {{ s.q_number }}</h5>
                        <div id="f__wrapp">
                            <div id="p__w">
                                <a href="{% url 'assignment_app:view-assignment-pdf' s.pk %}" target="_blank"><i class="fa fa-file-pdf-o" aria-hidden="true"></i></a>
                            </div>
                            <div>
                                <h5 class="dt-c">{{ s.date_created }}</h5>
                            </div>
                            {% if s.status == 'graded' %}
                                <div>
                                    <h5 style="color: green;">{{ s.status }}</h5>
                                </div>
                                <div id="ed">
                                    <a style="color: green;" href="#"><i class="fa fa-check" aria-hidden="true"></i></a>
                                </div>
                            {% else %}
                                <div>
                                    <h5 style="color: red;">{{ s.status }}</h5>
                                </div>
                                <div id="ed">
                                    <a style="color: red;" href="#"><i class="fa fa-check" aria-hidden="true"></i></a>
                                </div>
                            {% endif %}
                            
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <hr style="background-color: honeydew;">
        <form method="POST" action="." enctype="multipart/form-data" id="f__w">{% csrf_token %}
                {{ form|crispy }}
            <div class="form-group" id="b__w">
                <div>
                    <button class="btn btn-outline-info" type="submit">Score student</button>
                </div>
            </div>
        </form>
    </div>
    
{% endblock %}

assignment/templates/assignment/submission_denied.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
    <div class="denied-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body text-center p-2" id="text-wrap">
                        <a href="{% url 'assignment_app:submit-assignment' cur_user i_n %}"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>
                        Operational error!!!
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}